### ISSUE TITLE
audio signal not recognizable using ESP32-Send example

### ISSUE THREAD

**Issue by kamaljohnson** [chirp/chirp-arduino#15] opened 2019-08-13 08:28 UTC
My android application is not able to recognize the audio outup send by my esp32 using the ESP32Send code given in the examples
The android application is able to recognize the sample audio from the chirp configuration webpage
I am using the standard chirp protocol on both ESP32 and Android
[audio clip send by the ESP32](https://drive.google.com/open?id=0B9t0GHSdjg9LVW9LdU1ueWpXSWZiWVFoeHBUUk92NjNKN3pB)

**Comment by dinuchiriac** [comment] 2019-08-13 08:46
It sounds like your audio is distorted and sample-rate seems to be wrong, what protocol are you using?

**Comment by kamaljohnson** [comment] 2019-08-13 09:11
I am using the STANDARD protocol

**Comment by dinuchiriac** [comment] 2019-08-13 09:23
Can you try to use `16Khz-mono-embedded` which was designed to work on embedded devices?

**Comment by kamaljohnson** [comment] 2019-08-13 10:01
Its still not working. here is the [audio output](https://drive.google.com/open?id=0B9t0GHSdjg9LUkZVQ0JMekl2X2ViblV6YWxfVGlpOWNzcTRF)
I checked with multiple speakers

**Comment by dinuchiriac** [comment] 2019-08-13 10:12
The sample-rate sounds ok now but the audio is still very distorted, can you try to `setVolume` to something like `0.2f`. Also, can you take a recording in a wav format? Audio compression in different formats can decrease the recording quality.

**Comment by kamaljohnson** [comment] 2019-08-13 10:38
I tried setting the VOLUME to 0.2f as you told but the problem is still there, [audio clip](https://drive.google.com/open?id=0B9t0GHSdjg9LWjdDbWtwLTBaQ2llZDVMUUlGMGtsU3o2QUFZ)

**Comment by dinuchiriac** [comment] 2019-08-21 16:29
@joextodd What's the status of the issue, any updates? @kamaljohnson   did you fix your problem in the end?

**Comment by joextodd** [comment] 2019-08-21 16:30
I belive @kamaljohnson is moving over to the recommended digital I2S output rather than using the onboard DAC. Closing issue.

**Closed by joextodd** 2019-08-21 16:30 UTC
