### ISSUE TITLE
Creating Chirps with Audio API and receiving on Nano 33 BLE Sense

### ISSUE THREAD

**Issue by hansamann** [chirp/chirp-arduino#17] opened 2019-08-26 11:44 UTC
Hi all,

I am using the basic receive example for the Arduino 33 BLE Sense and uploaded the sketch successfully - I also set the 16khz-mono-embedded protocol and changed the credentials accordingly. When I open the serial monitor, I can see that it's listening...

Now I thought using the Swagger UI "try  it" / REST Audio API is a great idea to create the audio files for tetsting. The Payload is somethign like "000102" for 0, 1, 2 and protocol set to 16khz-mono-embedded. The audio generated creates a hearavble chirp.

On the serial monitor, I can see it goes into receiving mode and does not thrrow an error. But the data received is always garbage, e.g. some question marks or so. I was expecting that I could simply encode a "hello" into hex, have the audio generated and the receiving println would show me a "hello" - wrong?

**Comment by dinuchiriac** [comment] 2019-08-26 13:06
The "garbage" you see on the serial is probably due to the wrong data conversion.
The SDK operates in byte array so you'll have to convert your hex string to a byte array before sending and do the reverse on the receiving side,  see more details about that on the [documentation/payloads](https://developers.chirp.io/docs/using-chirp/payloads#hexstrings) page

**Comment by joextodd** [comment] 2019-08-27 09:51
@hansamann please try to use the following payload with the Audio API - `68656c6c6f`. 

You should see "hello" printed on the Nano 33 Serial Monitor.

**Comment by joextodd** [comment] 2019-09-30 09:47
Assuming the issue is resolved by the above suggestion.

**Closed by joextodd** 2019-09-30 09:47 UTC
